services:
  postgres:
    image: postgres:16
    container_name: xeri-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: xeri_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
